# Generated by Django 4.0.3 on 2022-04-19 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 수정일'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='last_modified_writter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faq',
            name='writer',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faq_creater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone_number', models.TextField(verbose_name='답변수신 폰번호')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('last_modified_writter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inq_modifier', to=settings.AUTH_USER_MODEL)),
                ('writter', models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inq_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수정일')),
                ('last_modified_writter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_modifier', to=settings.AUTH_USER_MODEL)),
                ('ref_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supports.inquiry')),
                ('writter', models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ans_creater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
