# Generated by Django 4.0.3 on 2022-04-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0002_alter_faq_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='CATEGORY_ONE', max_length=80, verbose_name='질문 제목'),
        ),
    ]
