# Generated by Django 4.0.3 on 2022-04-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0003_alter_faq_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('1', '일반'), ('2', '계정'), ('3', '기타')], default='3', max_length=2, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(default='', max_length=80, verbose_name='질문 제목'),
        ),
    ]
