# Generated by Django 4.0.3 on 2022-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0006_alter_answer_created_by_alter_answer_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완려')], default='', max_length=5, verbose_name='질문 상태'),
            preserve_default=False,
        ),
    ]
